extractors:
    yahoo:
        queries:
          - symbols: all
    reddit:
        min_date: '2020-01-01'
        max_date: '2022-06-30'
        queries:
          - endpoint: comment
            min_score: 2
            words: all
          - endpoint: comment
            min_score: 2
            subreddits: all
          - endpoint: submission
            min_score: 2
            words: all
          - endpoint: submission
            min_score: 2
            subreddits: all

