extractors:
    yahoo:
        queries:
          - symbols: all
    reddit:
        min_date: '2020-01-01'
        max_date: '2022-06-30'
        queries:
          - endpoint: comment
            min_score: 3
            words: all
          - endpoint: comment
            min_score: 3
            subreddits: all
          - endpoint: submission
            min_score: 3
            words: all
          - endpoint: submission
            min_score: 3
            subreddits: all

transformers:
    sentiment:
        chunk_size: 100
        processes: auto
